// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzUssW6IZaLOYmtaWKj2I5s6R72HDKsA',
    appId: '1:762208438330:web:a747c7cb4206d2b5814d03',
    messagingSenderId: '762208438330',
    projectId: 'cervezapp-3fcfd',
    authDomain: 'cervezapp-3fcfd.firebaseapp.com',
    databaseURL: 'https://cervezapp-3fcfd-default-rtdb.firebaseio.com',
    storageBucket: 'cervezapp-3fcfd.appspot.com',
    measurementId: 'G-CL2JZERXZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMkPb2DJgcPDoDqzY5TF2x_7AnKax8xo',
    appId: '1:762208438330:android:fc6ded3f13fb38db814d03',
    messagingSenderId: '762208438330',
    projectId: 'cervezapp-3fcfd',
    databaseURL: 'https://cervezapp-3fcfd-default-rtdb.firebaseio.com',
    storageBucket: 'cervezapp-3fcfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXHL-vzbMNPnDCEqFu2RbpO131YyyYWcU',
    appId: '1:762208438330:ios:6200feb3f94801f1814d03',
    messagingSenderId: '762208438330',
    projectId: 'cervezapp-3fcfd',
    databaseURL: 'https://cervezapp-3fcfd-default-rtdb.firebaseio.com',
    storageBucket: 'cervezapp-3fcfd.appspot.com',
    iosClientId: '762208438330-6e5eb82o3fsirr9oun9v2dt0is6vvmlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cervezapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXHL-vzbMNPnDCEqFu2RbpO131YyyYWcU',
    appId: '1:762208438330:ios:6200feb3f94801f1814d03',
    messagingSenderId: '762208438330',
    projectId: 'cervezapp-3fcfd',
    databaseURL: 'https://cervezapp-3fcfd-default-rtdb.firebaseio.com',
    storageBucket: 'cervezapp-3fcfd.appspot.com',
    iosClientId: '762208438330-6e5eb82o3fsirr9oun9v2dt0is6vvmlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cervezapp2',
  );
}
